arb-dir: lib/l10n
template-arb-file: app_en.arb
output-dir: lib/l10n/generated
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales:
  - en
  - ja
nullable-getter: false
required-resource-attributes: true
format: true
use-named-parameters: true
